#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES

#define TAILLE_TAG 255
#define TAILLE_USER 255
#define TAILLE_ECOUTE_MAX 1000
#define TAILLE_PATH 1024
#define TAILLE_LIST_ATTR 1000
#define TAILLE_ATTR TAILLE_TAG + TAILLE_USER + 1

#endif